### ISSUE TITLE
Create a sample program for REST API server and DB backend

### ISSUE THREAD

**Issue by oomichi** [oomichi/miscellany#8]
Requirements
- Python
- OpenAPI (generates REST API server for Python flask)
- SQLAlchemy (to avoid many definitions for different DBs like PostgreSQL, MySQL and sqlite, etc.)
- https://github.com/jdkandersson/OpenAlchemy (to avoid duplicated definition for SQLAlchemy)

OpenAlchemy's development seems to stop.
An active alternative is better if I can find.

Tasks:
- [x] Implemet REST API service with flask which is generated from openapi
- [x] Containerize the app
- [x] Implement DB store from REST API operation with SQLAlchemy 
- [x] Implement POST and specific GET methods

References:
- https://github.com/spec-first/connexion/blob/main/examples/sqlalchemy/orm.py

**Comment by oomichi** [comment]
```
$ podman run -p 8080:8080 openapi_server
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/src/app/openapi_server/__main__.py", line 5, in <module>
    from openapi_server import encoder
  File "/usr/src/app/openapi_server/encoder.py", line 1, in <module>
    from connexion.apps.flask_app import FlaskJSONEncoder
ModuleNotFoundError: No module named 'connexion.apps.flask_app'
```

**Comment by oomichi** [comment]
```
# pwd
/usr/local/lib/python3.11/site-packages/connexion/apps
# ls
__init__.py  __pycache__  abstract.py  asynchronous.py  flask.py
```
There is connexion.apps.flask, not connexion.apps.flask_app

flask generator of openapi-generator depends on old connexion.
commits of connexion:
- 45468a14e64de72ec420f771a0b34f5f509ba405: Rename FlaskJSONEncoder to FlaskJSONProvider
- edb0381af34ad2a35aab94569f503b85aa1ba964: connexion/apps/flask_app.py is renamed to connexion/apps/flask.py

The installed version is 3.0.1. might need to cap under 3.0.0 in requirements I guess.
```
Collecting connexion>=2.6.0 (from connexion[swagger-ui]>=2.6.0->-r requirements.txt (line 1))
  Downloading connexion-3.0.1-py3-none-any.whl.metadata (12 kB)
```
Bingo!
After adding the following change into requirements.txt, that works
```
connexion[swagger-ui] >= 2.6.0, < 3.0.0; python_version>="3.6"
```
